# Author: aics-ylchiang (Yu-Lun Chiang)
# Description: Normal DevOps pipeline

name: $(SourceBranchName)_$(Date:yyyy-MM-dd)_$(Rev:r)

trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "CodeQuality"

    jobs:
      - job: "HelloWorld"

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.9"
            displayName: "Use Python 3.9"

          - script: |
              echo "I'm here. Hello World."
            displayName: "Install dependencies"
